-- global_migration.sql
-- Esquema completo + datos de arranque para despliegue/migración.
BEGIN;

-- ------------------------------------------------------------
-- Types
-- ------------------------------------------------------------

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_status') THEN
        CREATE TYPE user_status AS ENUM ('ACTIVE', 'INACTIVE', 'BLOCKED');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'client_status') THEN
        CREATE TYPE client_status AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED');
    END IF;
END $$;

-- ------------------------------------------------------------
-- Geography
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS country (
    country_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_name VARCHAR(100) NOT NULL,
    country_description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS department_region (
    d_region_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    d_region_name VARCHAR(100) NOT NULL,
    d_region_description VARCHAR(255),
    country_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_department_region_country
        FOREIGN KEY (country_id)
        REFERENCES country(country_id)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS city (
    city_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_name VARCHAR(100) NOT NULL,
    city_description VARCHAR(255),
    postal_code VARCHAR(20),
    d_region_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_city_department_region
        FOREIGN KEY (d_region_id)
        REFERENCES department_region(d_region_id)
        ON DELETE RESTRICT
);

-- ------------------------------------------------------------
-- Security
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- Client
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    phone VARCHAR(50),
    document_type VARCHAR(20) NOT NULL,
    document_number VARCHAR(50) NOT NULL UNIQUE,
    business_name VARCHAR(150) NOT NULL,
    address VARCHAR(200),
    status client_status NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- Users
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    status user_status NOT NULL DEFAULT 'ACTIVE',
    city_id BIGINT NOT NULL,
    client_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_app_user_username UNIQUE (username),
    CONSTRAINT fk_app_user_city
        FOREIGN KEY (city_id)
        REFERENCES city(city_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_app_user_client
        FOREIGN KEY (client_id)
        REFERENCES client(id)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user
        FOREIGN KEY (user_id)
        REFERENCES app_user(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_role_role
        FOREIGN KEY (role_id)
        REFERENCES role(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS role_permission (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permission_role
        FOREIGN KEY (role_id)
        REFERENCES role(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_role_permission_permission
        FOREIGN KEY (permission_id)
        REFERENCES permission(id)
        ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- Warehouses
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS warehouse (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    description TEXT,
    capacity NUMERIC(12,2),
    available_capacity_m2 NUMERIC(12,2) NOT NULL,
    total_capacity_m2 NUMERIC(12,2) NOT NULL,
    location VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    city_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_warehouse_city
        FOREIGN KEY (city_id)
        REFERENCES city(city_id)
        ON DELETE RESTRICT
);

-- ------------------------------------------------------------
-- Auth persistence
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS auth_refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(700) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auth_revoked_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(700) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auth_password_reset_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(700) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auth_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(40) NOT NULL,
    email VARCHAR(255) NOT NULL,
    ip_address VARCHAR(100),
    details VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- Indexes
-- ------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_app_user_client_id ON app_user (client_id);
CREATE INDEX IF NOT EXISTS idx_auth_refresh_token_email ON auth_refresh_token (email);
CREATE INDEX IF NOT EXISTS idx_auth_refresh_token_expires_at ON auth_refresh_token (expires_at);
CREATE INDEX IF NOT EXISTS idx_auth_revoked_token_expires_at ON auth_revoked_token (expires_at);
CREATE INDEX IF NOT EXISTS idx_auth_password_reset_token_email ON auth_password_reset_token (email);
CREATE INDEX IF NOT EXISTS idx_auth_password_reset_token_expires_at ON auth_password_reset_token (expires_at);
CREATE INDEX IF NOT EXISTS idx_auth_audit_log_event_type ON auth_audit_log (event_type);
CREATE INDEX IF NOT EXISTS idx_auth_audit_log_created_at ON auth_audit_log (created_at);

-- ------------------------------------------------------------
-- Seed data
-- ------------------------------------------------------------

INSERT INTO role (name, description)
VALUES
    ('ADMIN', 'Platform administrator'),
    ('WAREHOUSE_EMPLOYEE', 'Warehouse operational user'),
    ('WAREHOUSE_SUPERVISOR', 'Warehouse supervisor user'),
    ('USER', 'Standard authenticated user (legacy)'),
    ('SALES_AGENT', 'Commercial user'),
    ('CLIENT', 'Client role')
ON CONFLICT (name) DO NOTHING;

INSERT INTO country (country_name, country_description)
SELECT 'Colombia', 'Default country for local bootstrap'
WHERE NOT EXISTS (SELECT 1 FROM country WHERE country_name = 'Colombia');

INSERT INTO department_region (d_region_name, d_region_description, country_id)
SELECT 'Cundinamarca', 'Default region for local bootstrap', c.country_id
FROM country c
WHERE c.country_name = 'Colombia'
  AND NOT EXISTS (SELECT 1 FROM department_region WHERE d_region_name = 'Cundinamarca');

INSERT INTO city (city_name, city_description, postal_code, d_region_id)
SELECT 'Bogota', 'Default city for local bootstrap', '110111', r.d_region_id
FROM department_region r
WHERE r.d_region_name = 'Cundinamarca'
  AND NOT EXISTS (SELECT 1 FROM city WHERE city_name = 'Bogota');

INSERT INTO client (name, email, phone, document_type, document_number, business_name, address, status)
SELECT 'Cliente Demo', 'cliente.demo@nexus.local', '3000000000', 'NIT', '900000001', 'Cliente Demo SAS', 'Bogota', 'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM client WHERE email = 'cliente.demo@nexus.local');

-- Dev users (admin, cliente_demo) are not inserted here to avoid exposing passwords in the repo.
-- Create them via POST /api/auth/register and assign roles in DB, or run seed_current_api_dev.sql after adding users locally.

INSERT INTO warehouse (name, description, capacity, available_capacity_m2, total_capacity_m2, location, active, city_id)
SELECT 'Bodega Central', 'Bodega inicial para desarrollo local', 250.00, 250.00, 250.00, 'Bogota', TRUE, c.city_id
FROM city c
WHERE c.city_name = 'Bogota'
  AND NOT EXISTS (SELECT 1 FROM warehouse WHERE name = 'Bodega Central')
LIMIT 1;

COMMIT;
